HIP CPU
tinygrad/tinygrad pull request #1419
Opened 2023-08-03 19:20 UTC by dc-dc-dc

Got it working but it is brutally slow right now, with 16 cores it takes almost an hour just to run `test/test_ops.py`

2023-08-03 19:30 UTC, tinyb0t commented
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/runtime/ops_hip.py               63              20
------------------------------------------------------------
lines added in the tinygrad folder: 43
```

2023-08-03 19:54 UTC, prusnak commented
`'utf-8'` is the default encoding for `encode()` and `decode()`, so you can just call `.encode()`/`.decode()`

2023-08-05 16:35 UTC, dc-dc-dc commented
current bottleneck is that it has to compile the runtime for each kernel as HIP-CPU is missing `hipModuleLaunchKernel` and instead uses an inline macro to launch the kernel.

2023-08-12 20:17 UTC, dc-dc-dc commented
Found something that is closer to whats needed `hip::detail::launch_kernel_from_so` but currently getting seg faults when trying to use it

2023-08-15 11:49 UTC, aseok commented
@dc-dc-dc Is there any of already proposed bounties relates to your pr?

2023-08-15 15:39 UTC, geohot commented
Locked the bounty for you.

2023-08-17 14:07 UTC, prusnak requested changes

2023-08-17 14:07 UTC, prusnak commented on tinygrad/runtime/ops_hip.py
> +        subprocess.check_output(args=('clang -g -std=c++20 --stdlib=libstdc++ -shared -O2 -Wall -Werror -x c++ -ltbb -ltbbmalloc -fPIC --rtlib=compiler-rt - -o '+fn+'.tmp').split(), input=prg.encode(
this is a race condition - add process id to tmp file name - see `ops_clang.py` to see how it is done:

https://github.com/tinygrad/tinygrad/blob/a293c18d345a45ff7a315c8fb5da17437c129949/tinygrad/runtime/ops_clang.py#L38

2023-08-28 03:02 UTC, wozeparrot commented
Update on this?

2023-08-28 14:07 UTC, dc-dc-dc commented
Will close and let someone else continue, I still think `hip::detail::launch_kernel_from_so` is the right path forward as using `hipLaunchKernelGGL` requires rebuilding the runtime which takes way too long and times out in CI

Tracking #1700

2023-08-28 14:07 UTC, closed without merging

2023-08-30 18:33 UTC, nimlgen commented
`hip::detail::launch_kernel_from_so` does not support any kernel arguments at all. Call to `launch` [passes empty args tuple](https://github.com/ROCm-Developer-Tools/HIP-CPU/blob/master/src/include/hip/detail/api.hpp#L636) and seems there is a [comment](https://github.com/ROCm-Developer-Tools/HIP-CPU/blob/master/src/include/hip/detail/api.hpp#L638).

Compilation time of "HIP-CPU" include-only templated library is huge. I am not sure we can do anything with this, since even `blockIdx`, which is inside each kernel, can take up to 5-20s to compile.